"""unique message stack position

Revision ID: 6217818b6c73
Revises: cf70fc8772ac
Create Date: 2026-07-14 16:14:18.623704+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6217818b6c73'
down_revision: Union[str, None] = 'cf70fc8772ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_message_stack_position', 'message', ['stack_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_message_stack_position', 'message', type_='unique')
    # ### end Alembic commands ###
