"""baseline schema

Revision ID: cf70fc8772ac
Revises: 
Create Date: 2026-07-14 15:50:51.026525+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy.vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf70fc8772ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# All PostgreSQL enum types are managed explicitly (created once up front,
# dropped on downgrade) so migrations stay idempotent and fully reversible.
# Inline columns reference them via _enum() with create_type=False so CREATE
# TABLE never re-emits CREATE TYPE.
_ENUMS = {
    "agentrole": postgresql.ENUM(
        'application_security_supervisor', 'governance_risk_compliance_supervisor',
        'detection_incident_response_supervisor', 'offensive_security_supervisor',
        'vulnerability_management_supervisor', 'custom_supervisor',
        'application_security_architect', 'detection_incident_response_architect',
        'security_engineering_architect', 'application_security_engineer',
        'governance_risk_compliance_engineer', 'detection_incident_response_engineer',
        'offensive_security_engineer', 'vulnerability_management_engineer',
        'application_security_analyst', 'governance_risk_compliance_analyst',
        'detection_incident_response_analyst', 'offensive_security_analyst',
        'vulnerability_management_analyst', 'custom_supporting_agent',
        name='agentrole',
    ),
    "agenttype": postgresql.ENUM('supporting', 'supervisor', name='agenttype'),
    "tooltype": postgresql.ENUM('HTTP', 'MCP', 'LOGICAL', name='tooltype'),
    "role": postgresql.ENUM('ADMIN', 'USER', name='role'),
    "authtype": postgresql.ENUM('BEARER', 'HEADER', name='authtype'),
    "provider": postgresql.ENUM('ANTHROPIC', 'OPENAI', 'BEDROCK', name='provider'),
    "stackscheduletype": postgresql.ENUM('interval', 'fixed', 'recurring', name='stackscheduletype'),
    "stackschedulerecurrence": postgresql.ENUM('weekly', 'monthly', name='stackschedulerecurrence'),
    "stackscheduletimestatus": postgresql.ENUM('pending', 'completed', 'failed', name='stackscheduletimestatus'),
    "stackschedulerunstatus": postgresql.ENUM('pending', 'running', 'completed', 'failed', name='stackschedulerunstatus'),
}


def _enum(name: str) -> postgresql.ENUM:
    """Reference a pre-created enum without re-emitting CREATE TYPE."""
    return postgresql.ENUM(name=name, create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    bind = op.get_bind()
    for enum in _ENUMS.values():
        enum.create(bind, checkfirst=True)

    op.create_table('prompt',
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', _enum('agentrole'), nullable=True),
    sa.Column('agent_type', _enum('agenttype'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', _enum('role'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('credential',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_embedding_hnsw', 'memory', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('stack',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_position', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toolset',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_required', sa.Boolean(), nullable=False),
    sa.Column('auth_type', _enum('authtype'), nullable=True),
    sa.Column('header', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', _enum('tooltype'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', _enum('provider'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id')
    )
    op.create_table('message',
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_stack_id'), 'message', ['stack_id'], unique=False)
    op.create_table('stack_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('schedule_type', _enum('stackscheduletype'), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('recurrence', _enum('stackschedulerecurrence'), nullable=True),
    sa.Column('recurrence_day', sa.Integer(), nullable=True),
    sa.Column('recurrence_hour', sa.Integer(), nullable=False),
    sa.Column('recurrence_minute', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('verbose', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stack_schedule_stack_id'), 'stack_schedule', ['stack_id'], unique=False)
    op.create_index(op.f('ix_stack_schedule_user_id'), 'stack_schedule', ['user_id'], unique=False)
    op.create_table('tool',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type', _enum('tooltype'), nullable=False),
    sa.Column('toolset_id', sa.Integer(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['toolset_id'], ['toolset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_toolset_credential',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('toolset_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], ),
    sa.ForeignKeyConstraint(['toolset_id'], ['toolset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'toolset_id')
    )
    op.create_table('agent',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_type', _enum('agenttype'), nullable=True),
    sa.Column('role', _enum('agentrole'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('llm_id', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['llm_id'], ['llm.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stack_schedule_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('status', _enum('stackscheduletimestatus'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['stack_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stack_schedule_time_run_at'), 'stack_schedule_time', ['run_at'], unique=False)
    op.create_index(op.f('ix_stack_schedule_time_schedule_id'), 'stack_schedule_time', ['schedule_id'], unique=False)
    op.create_table('toolset_tool_link',
    sa.Column('toolset_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.ForeignKeyConstraint(['toolset_id'], ['toolset.id'], ),
    sa.PrimaryKeyConstraint('toolset_id', 'tool_id')
    )
    op.create_table('agent_stack_link',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'stack_id')
    )
    op.create_table('agent_tool_link',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    op.create_table('agent_toolset_link',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('toolset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['toolset_id'], ['toolset.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'toolset_id')
    )
    op.create_table('stack_schedule_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('schedule_time_id', sa.Integer(), nullable=True),
    sa.Column('stack_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', _enum('stackschedulerunstatus'), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('message_start_id', sa.Integer(), nullable=True),
    sa.Column('message_end_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['stack_schedule.id'], ),
    sa.ForeignKeyConstraint(['schedule_time_id'], ['stack_schedule_time.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stack_schedule_run_run_id'), 'stack_schedule_run', ['run_id'], unique=False)
    op.create_index(op.f('ix_stack_schedule_run_schedule_id'), 'stack_schedule_run', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_stack_schedule_run_schedule_time_id'), 'stack_schedule_run', ['schedule_time_id'], unique=False)
    op.create_index(op.f('ix_stack_schedule_run_stack_id'), 'stack_schedule_run', ['stack_id'], unique=False)
    op.create_index(op.f('ix_stack_schedule_run_user_id'), 'stack_schedule_run', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stack_schedule_run_user_id'), table_name='stack_schedule_run')
    op.drop_index(op.f('ix_stack_schedule_run_stack_id'), table_name='stack_schedule_run')
    op.drop_index(op.f('ix_stack_schedule_run_schedule_time_id'), table_name='stack_schedule_run')
    op.drop_index(op.f('ix_stack_schedule_run_schedule_id'), table_name='stack_schedule_run')
    op.drop_index(op.f('ix_stack_schedule_run_run_id'), table_name='stack_schedule_run')
    op.drop_table('stack_schedule_run')
    op.drop_table('agent_toolset_link')
    op.drop_table('agent_tool_link')
    op.drop_table('agent_stack_link')
    op.drop_table('toolset_tool_link')
    op.drop_index(op.f('ix_stack_schedule_time_schedule_id'), table_name='stack_schedule_time')
    op.drop_index(op.f('ix_stack_schedule_time_run_at'), table_name='stack_schedule_time')
    op.drop_table('stack_schedule_time')
    op.drop_table('agent')
    op.drop_table('user_toolset_credential')
    op.drop_table('tool')
    op.drop_index(op.f('ix_stack_schedule_user_id'), table_name='stack_schedule')
    op.drop_index(op.f('ix_stack_schedule_stack_id'), table_name='stack_schedule')
    op.drop_table('stack_schedule')
    op.drop_index(op.f('ix_message_stack_id'), table_name='message')
    op.drop_table('message')
    op.drop_table('llm')
    op.drop_table('toolset')
    op.drop_table('stack')
    op.drop_index('ix_memories_embedding_hnsw', table_name='memory', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('memory')
    op.drop_table('credential')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('prompt')

    bind = op.get_bind()
    for enum in _ENUMS.values():
        enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
